"""empty message

Revision ID: 3cd5d0c7b792
Revises: f2e599152333
Create Date: 2020-03-17 18:01:58.649075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd5d0c7b792'
down_revision = 'f2e599152333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('x1', sa.String(length=32), nullable=True),
    sa.Column('x2', sa.String(length=32), nullable=True),
    sa.Column('x3', sa.String(length=32), nullable=True),
    sa.Column('x4', sa.String(length=32), nullable=True),
    sa.Column('x5', sa.String(length=32), nullable=True),
    sa.Column('x6', sa.String(length=32), nullable=True),
    sa.Column('x7', sa.String(length=32), nullable=True),
    sa.Column('x8', sa.String(length=32), nullable=True),
    sa.Column('x9', sa.String(length=32), nullable=True),
    sa.Column('x10', sa.String(length=32), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'student_id')
    )
    op.create_table('student_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('x1', sa.String(length=32), nullable=True),
    sa.Column('x2', sa.String(length=32), nullable=True),
    sa.Column('x3', sa.String(length=32), nullable=True),
    sa.Column('x4', sa.String(length=32), nullable=True),
    sa.Column('x5', sa.String(length=32), nullable=True),
    sa.Column('x6', sa.String(length=32), nullable=True),
    sa.Column('x7', sa.String(length=32), nullable=True),
    sa.Column('x8', sa.String(length=32), nullable=True),
    sa.Column('x9', sa.String(length=32), nullable=True),
    sa.Column('x10', sa.String(length=32), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_properties')
    op.drop_table('class')
    # ### end Alembic commands ###
