"""empty message

Revision ID: 94116fcee6fb
Revises: 9fa44a48b40c
Create Date: 2020-03-17 16:03:18.828614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94116fcee6fb'
down_revision = '9fa44a48b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'posted')
    # ### end Alembic commands ###
