"""empty message

Revision ID: b20ce58399b3
Revises: 6b50485dd001
Create Date: 2020-03-20 23:28:55.980687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20ce58399b3'
down_revision = '6b50485dd001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('section', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'section')
    # ### end Alembic commands ###
