"""empty message

Revision ID: f104a02a3add
Revises: 36727c848fa4
Create Date: 2020-06-06 20:13:13.651919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f104a02a3add'
down_revision = '36727c848fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specifications', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specifications', 'priority')
    # ### end Alembic commands ###
