"""empty message

Revision ID: f2e599152333
Revises: 1c0211ba8648
Create Date: 2020-03-17 16:27:53.970302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e599152333'
down_revision = '1c0211ba8648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('commenter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parameters', 'users', ['commenter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.drop_column('parameters', 'commenter_id')
    # ### end Alembic commands ###
